const veterinarias = [
    {
        id: 'vet1',
        titulo: 'Veterinaria Pattas',
        texto: 'L.D.Colosio',
        imagen: '../img/veterinarias/vete6.jpg',
        enlace: '',
        colonia:'colosio',
        servicio:'domicilio',
        estado:"abierto",
      },
      {
          id: 'vet2',
          titulo: 'veterinaria Animalocos',
          texto: 'L.D.Colosio',
          imagen: '../img/veterinarias/vete10.jpg',
          enlace: '',
          colonia:'colosio',
          servicio:'domicilio',
          estado:"cerrado",
        },
        {
          id: 'vet3',
          titulo: 'veterinaria Santa Luicia',
          texto: 'L.D.Colosio',
          imagen: '../img/veterinarias/vete3.jpg',
          enlace: '',
          colonia:'colosio',
          servicio:'normal',
          estado:"abierto",
        },
        {
          id: 'vet4',
          titulo: 'veterinaria ZooCare',
          texto: 'costera',
          imagen: '../img/veterinarias/vete4.jpg',
          enlace: '',
          colonia:'coloso',
          servicio:'normal',
          estado:"cerrado",
        },
        {
          id: 'vet5',
          titulo: 'veterinaria Pets',
          texto: 'L.D.Colosio',
          imagen: '../img/veterinarias/vete5.jpg',
          enlace: '',
          colonia:'colosio',
          servicio:'domicilio',
          estado:"abierto",
        },
        {
          id: 'vet6',
          titulo: 'veterinaria Pets',
          texto: 'L.D.Colosio',
          imagen: '../img/veterinarias/vete6.jpg',
          enlace: '',
          colonia:'colosio',
          servicio:'domicilio',
          estado:"abierto",
        },
        {
          id: 'vet7',
          titulo: 'veterinaria Pets',
          texto: 'L.D.Colosio',
          imagen: '../img/veterinarias/vete7.jpg',
          enlace: '',
          colonia:'colosio',
          servicio:'domicilio',
          estado:"abierto",
        },
]